### ISSUE TITLE
DEBUG Range

### ISSUE THREAD

**Issue by atbu** [F3Community/F3com-data#78]
The Documentation:

https://github.com/F3Community/F3com-data/blob/3b0c48fe7c58bcf8f2f5ba843f541cb54408647c/framework-variables/main.md

says:
> While developing your application, it's best to set the debug level to maximum so you can trace all errors to their root cause:
> $f3->set('DEBUG',3);

and later

> DEBUG can have values ranging from 0 (stack trace suppressed) to 2 (most verbose with classes & functions calls logs).

This is unclear shouldn´t either first be two or second quote say 3?

– anatol

**Comment by Rayne** [comment]
The `DEBUG` levels are ranging from `0` to `3` (or [`PHP_INT_MAX`](https://github.com/bcosca/fatfree-core/blob/baa5472c3055e700b81368d8ca8241d59f7dcc36/base.php#L1136), but `3` is convenient and the highest official number).

Fixed with https://github.com/F3Community/F3com-data/commit/f0707c7f52fca1c5331b59226e9a96df915e86f6.
